# Numpy Tutorial

**NumPy**: Numerical Python

**Advantages of NumPy**:
1. Allows several mathematical operations
2. Faster operations

### Setup

In [47]:
# download the library
!pip install numpy

In [46]:
# import the library
import numpy as np

### NumPy speed

In [2]:
from time import process_time

In [5]:
python_list = [i for i in range(1000000)]

start_time = process_time()
python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time-start_time)

0.06878739699999992


In [6]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()
np_array += 5

end_time = process_time()

print(end_time - start_time)

0.001325765999999895


### NumPy array

In [7]:
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# Creating a 1D array
a = np.array([1, 2, 3, 4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [11]:
b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [14]:
 c = np.array([
         [1, 2, 3, 4],
         [5, 6, 7, 8],
    ], dtype=float
)
c, c.shape

(array([[1., 2., 3., 4.],
        [5., 6., 7., 8.]]),
 (2, 4))

### Initial placeholders in NumPy arrays

In [15]:
x = np.zeros((4, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
y = np.ones((5, 4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
z = np.full((5, 4), 5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [22]:
# random values
b = np.random.random((3, 4))
print(b)

[[0.70062755 0.9955023  0.62551732 0.86262794]
 [0.95015003 0.40806251 0.84725967 0.80584137]
 [0.87206182 0.47429077 0.24072186 0.51353841]]


In [23]:
# random integer values matrix within a specific range
c = np.random.randint(10, 100, (3, 5))

In [24]:
c

array([[54, 92, 40, 51, 69],
       [50, 34, 34, 46, 84],
       [10, 87, 92, 26, 62]])

In [26]:
# array of evenly spaced values --> specify number of values
d = np.linspace(10, 30, 5)
d

array([10., 15., 20., 25., 30.])

In [27]:
# array of evenly spaced values --> specify step
e = np.arange(10, 30, 6)
e

array([10, 16, 22, 28])

In [28]:
# convert a list to NumPy array
list2 = [[10, 20, 30, 40], [50, 50, 60, 70]]
np_array2 = np.asarray(list2)
np_array2

array([[10, 20, 30, 40],
       [50, 50, 60, 70]])

### Analyzing a NumPy array

In [29]:
c = np.random.randint(10, 90, (5, 5))
print(c)

[[37 10 26 15 74]
 [78 28 30 27 87]
 [66 28 41 28 69]
 [78 11 69 77 43]
 [32 75 33 56 77]]


In [30]:
# array dimensions
print(c.shape)

(5, 5)


In [31]:
# number of dimensions
print(c.ndim)

2


In [32]:
# number of elements in a matrix
print(c.size)

25


In [33]:
# checking the datatype of values in the array
print(c.dtype)

int64


### Mathematical operations

In [34]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2) # list concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 20, (3, 3))

print(a, b, sep='\n')

[[7 2 1]
 [0 2 0]
 [2 3 8]]
[[ 1  4  2]
 [10  4  9]
 [ 3 19  8]]


In [37]:
print(a+b) # element wise addition
print(a-b) # element wise subtraction
print(a*b) # element wise multiplication
print(a/b) # element wise division

[[ 8  6  3]
 [10  6  9]
 [ 5 22 16]]
[[  6  -2  -1]
 [-10  -2  -9]
 [ -1 -16   0]]
[[ 7  8  2]
 [ 0  8  0]
 [ 6 57 64]]
[[7.         0.5        0.5       ]
 [0.         0.5        0.        ]
 [0.66666667 0.15789474 1.        ]]


In [38]:
print(a)
print(b)

[[7 2 1]
 [0 2 0]
 [2 3 8]]
[[ 1  4  2]
 [10  4  9]
 [ 3 19  8]]


In [39]:
print(np.add(a, b)) # element wise addition
print(a)

[[ 8  6  3]
 [10  6  9]
 [ 5 22 16]]
[[7 2 1]
 [0 2 0]
 [2 3 8]]


In [40]:
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[  6  -2  -1]
 [-10  -2  -9]
 [ -1 -16   0]]
[[ 7  8  2]
 [ 0  8  0]
 [ 6 57 64]]
[[7.         0.5        0.5       ]
 [0.         0.5        0.        ]
 [0.66666667 0.15789474 1.        ]]


### Array manipultion

In [41]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[9 4 3]
 [3 4 0]]
(2, 3)


In [42]:
# transpose
array_transpose = np.transpose(array)
print(array_transpose)

[[9 3]
 [4 4]
 [3 0]]


In [43]:
array_transpose2 = array.T
print(array_transpose2.shape)

(3, 2)


In [44]:
# reshaping an array
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[2 6 8]
 [6 8 1]]
(2, 3)


In [45]:
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[2 6]
 [8 6]
 [8 1]]
(3, 2)
