# Matrix Operations

In [1]:
import numpy as np

### Matrix addition

In [3]:
A = np.array([
    [2, 3],
    [4, 5],
])

B = np.array([
    [6, 7],
    [8, 9],
])

A + B

array([[ 8, 10],
       [12, 14]])

### Matrix subtraction

In [4]:
A = np.array([
    [2, 3],
    [4, 5],
])

B = np.array([
    [6, 7],
    [8, 9],
])

A - B

array([[-4, -4],
       [-4, -4]])

### Dimensions of a matrix

In [5]:
A.shape

(2, 2)

### Create a matrix with random values

In [11]:
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(20, size=(3, 3))
print(mat1, mat2, sep='\n')

[[5 4 9]
 [1 4 6]
 [6 8 7]]
[[ 2 11  8]
 [ 7 14 14]
 [ 1  8 11]]


In [12]:
print(np.add(mat1, mat2))
print(np.subtract(mat1, mat2))

[[ 7 15 17]
 [ 8 18 20]
 [ 7 16 18]]
[[  3  -7   1]
 [ -6 -10  -8]
 [  5   0  -4]]


### Multiplication

In [15]:
# Multiplying a matrix by a scaler
x = 5
X = np.random.randint(5, size=(3, 3))

print(X)
print(x * X)
print(np.multiply(x, X))

[[4 0 1]
 [1 0 3]
 [3 2 1]]
[[20  0  5]
 [ 5  0 15]
 [15 10  5]]
[[20  0  5]
 [ 5  0 15]
 [15 10  5]]


In [18]:
# Multiplying two matrices element wise:
X = np.random.randint(10, size=(3,3))
I = np.eye(3, 3)
print(X)
print(np.multiply(X, I))

[[8 4 7]
 [3 5 9]
 [1 9 7]]
[[8. 0. 0.]
 [0. 5. 0.]
 [0. 0. 7.]]


In [19]:
# Matrix multiplication
print(np.matmul(X, I))

[[8. 4. 7.]
 [3. 5. 9.]
 [1. 9. 7.]]


In [20]:
Y = np.random.randint(10, size=(3, 4))
print(np.matmul(X, Y))

[[116  70 117  50]
 [126  68  91  56]
 [140  54 101  78]]


In [21]:
print(np.dot(X, Y))

[[116  70 117  50]
 [126  68  91  56]
 [140  54 101  78]]
